import base64,os
b64="IyEvdXNyL2Jpbi9lbnYgcHl0aG9uMwppbXBvcnQgcmVxdWVzdHMsIGlvLCBvcywgdGltZSwgYm90bzMKZnJvbSBQSUwgaW1wb3J0IEltYWdlCgpGQUxfQVBJX0tFWSA9IFwiNjRiNzg2YzMtZDZiMS00ZmJiLTlkNDYtOTIxMWNlZWE1NTJmOmQ0NzJjZGY4YzY4YjRmZTg3MzU1N2NhMzNiZmIyNWViXCIKRkFMX0VORFBPSU5UID0gXCJodHRwczovL2ZhbC5ydW4vZmFsLWFpL2dwdC1pbWFnZS0xLjVcIgpTM19CVUNLRVQgPSBcImlzbmJpei1hc3NldHMtMTc2OTk2MjI4MFwiCg=="
open("/home/jdmal/workspace/ISNBIZ_Files/generate_hero_backgrounds.py","wb").write(base64.b64decode(b64))
print("partial")
